apiVersion: apps/v1
kind: Deployment
metadata:
  name: tux-racer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tux-racer
  template:
    metadata:
      labels:
        app: tux-racer
    spec:
      containers:
      - name: tux-racer
        image: 343218196114.dkr.ecr.us-east-1.amazonaws.com/tux-racer-js:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tux-racer-service
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: tux-racer
  type: LoadBalancer